[PHP]
; Custom PHP config for local dev
extension_dir = "C:\\Users\\user\\AppData\\Local\\Microsoft\\WinGet\\Packages\\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\\ext"

date.timezone = "Australia/Sydney"

; Enable required extensions
extension = pdo_mysql
extension = mysqli
